// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gerikullanim.Data;

namespace gerikullanim.Migrations
{
    [DbContext(typeof(gerikullanimContext))]
    partial class gerikullanimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("gerikullanim.Models.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuyuruAciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuyuruAdi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("kullaniciIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("kullaniciIdId");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("gerikullanim.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("gerikullanim.Models.Resim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DosyaAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuyuruId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DuyuruId");

                    b.ToTable("Resimler");
                });

            modelBuilder.Entity("gerikullanim.Models.Duyuru", b =>
                {
                    b.HasOne("gerikullanim.Models.Kullanici", "kullaniciId")
                        .WithMany("Duyurulari")
                        .HasForeignKey("kullaniciIdId");

                    b.Navigation("kullaniciId");
                });

            modelBuilder.Entity("gerikullanim.Models.Resim", b =>
                {
                    b.HasOne("gerikullanim.Models.Duyuru", "Duyurusu")
                        .WithMany("Resimler")
                        .HasForeignKey("DuyuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duyurusu");
                });

            modelBuilder.Entity("gerikullanim.Models.Duyuru", b =>
                {
                    b.Navigation("Resimler");
                });

            modelBuilder.Entity("gerikullanim.Models.Kullanici", b =>
                {
                    b.Navigation("Duyurulari");
                });
#pragma warning restore 612, 618
        }
    }
}
